### ISSUE TITLE
About the all model

### ISSUE THREAD

**Issue by XuJian1252878** [krshrimali/No-Reference-Image-Quality-Assessment-using-BRISQUE-Model#1]
First, thank you for providing the implementation of BRISQUE. 
And I want to know where the "allmodel" file used by svm comes from?
Does the "allmodel" file trained from the tid2013 or tid2008 dataset?

**Comment by krshrimali** [comment]
Thanks, @XuJian1252878. The `allmodel` file is borrowed from https://github.com/dsoellinger/blind_image_quality_toolbox/tree/master/%2Bbrisque. As far as I know, it's trained on TID2008 Dataset.

You can have a look at the blog for BRISQUE, if you find it useful: https://www.learnopencv.com/image-quality-assessment-brisque/

Thanks!

**Comment by XuJian1252878** [comment]
Thanks!
